-- ════════════════════════════════════════════════════════════════════
--  SEED: Exámenes de Capacitación — Comindustria
--  Ergonomía en Oficina + Riesgos Psicosociales y Salud Mental
-- ════════════════════════════════════════════════════════════════════

DO $$
DECLARE
  emp_id UUID := 'aed03706-baf4-412e-b30f-ab09f110c971';
  ex1_id UUID;
  ex2_id UUID;
BEGIN

-- ── EXAMEN 1: Ergonomía en Oficina ───────────────────────────────────
INSERT INTO examenes (empresa_id, nombre, descripcion, activo, puntaje_minimo)
VALUES (emp_id, 'Ergonomía en Oficina',
  'Capacitación sobre ergonomía, factores de riesgo disergonómico y prácticas en el puesto de trabajo.', true, 7)
RETURNING id INTO ex1_id;

INSERT INTO examen_preguntas (examen_id, orden, pregunta, opcion_a, opcion_b, opcion_c, opcion_d, correcta) VALUES
(ex1_id, 1,
  '¿Qué es la ergonomía?',
  'El estudio de la relación entre los trabajadores y su estación de trabajo para garantizar seguridad, comodidad y eficiencia',
  'El diseño de muebles de oficina',
  'La medición del rendimiento laboral',
  'El control de calidad en producción',
  'a'),
(ex1_id, 2,
  '¿Cuál es el beneficio principal de la ergonomía?',
  'Aumentar el costo de producción',
  'Reducir lesiones, errores, defectos y ausentismo del personal',
  'Incrementar las horas de trabajo',
  'Reducir el número de trabajadores',
  'b'),
(ex1_id, 3,
  '¿Cuál es la norma base legal de ergonomía en el Perú?',
  'D.S. 005-2012-TR',
  'Ley 29783',
  'Resolución Ministerial N°375-2008-TR',
  'D.S. 055-2010-EM',
  'c'),
(ex1_id, 4,
  '¿Cuál de estos es un factor de riesgo disergonómico?',
  'Buena iluminación',
  'Posturas de trabajo inadecuadas, movimientos repetitivos y sobreesfuerzos',
  'Uso de silla ergonómica',
  'Pausas activas frecuentes',
  'b'),
(ex1_id, 5,
  '¿Cuál es una característica del factor humano en ergonomía?',
  'Todas las personas tienen la misma figura y tamaño',
  'Las personas son diferentes en figuras, tamaños y limitaciones físicas y mentales',
  'Todas las personas tienen la misma capacidad física',
  'Los trabajadores no tienen limitaciones',
  'b'),
(ex1_id, 6,
  '¿Cuál de estos es un elemento de una estación de trabajo ergonómica?',
  'Escritorio pequeño y silla incómoda',
  'Mesa de trabajo espaciosa, buena iluminación y silla de calidad',
  'Herramientas de baja calidad',
  'Equipos distribuidos al azar',
  'b'),
(ex1_id, 7,
  'La fatiga visual puede manifestarse como:',
  'Dolor de cintura y espalda',
  'Dificultad de concentración y dolor de cabeza',
  'Irritación de ojos y pesadez en párpados',
  'Calambres en las piernas',
  'c'),
(ex1_id, 8,
  'La fatiga mental se caracteriza principalmente por:',
  'Irritación de ojos',
  'Dolor en muñecas y manos',
  'Dificultad de concentración y dolor de cabeza',
  'Hormigueos en miembros inferiores',
  'c'),
(ex1_id, 9,
  'Para cuidar la vista durante el trabajo en oficina se recomienda:',
  'Usar lentes oscuros todo el día',
  'Descansar la vista cada determinado tiempo y parpadear con frecuencia para mantener los ojos húmedos',
  'Trabajar con poca iluminación',
  'No usar computadora',
  'b'),
(ex1_id, 10,
  '¿Cuál es el objetivo principal de adaptar el trabajo al trabajador?',
  'Reducir el sueldo del trabajador',
  'Aumentar la carga laboral',
  'Garantizar que las operaciones se desarrollen con seguridad, sin fatiga excesiva y de forma eficiente',
  'Eliminar los descansos',
  'c');

-- ── EXAMEN 2: Riesgos Psicosociales y Salud Mental ───────────────────
INSERT INTO examenes (empresa_id, nombre, descripcion, activo, puntaje_minimo)
VALUES (emp_id, 'Riesgos Psicosociales y Salud Mental',
  'Capacitación sobre salud mental, estrés laboral, síndrome de burnout y técnicas prácticas de bienestar.', true, 7)
RETURNING id INTO ex2_id;

INSERT INTO examen_preguntas (examen_id, orden, pregunta, opcion_a, opcion_b, opcion_c, opcion_d, correcta) VALUES
(ex2_id, 1,
  '¿Cómo se define la salud mental?',
  'Ausencia de enfermedades físicas',
  'Estado de bienestar emocional, psicológico y social que afecta cómo pensamos, sentimos y actuamos',
  'Solo el estado emocional de una persona',
  'La capacidad de trabajar sin descanso',
  'b'),
(ex2_id, 2,
  '¿Qué son los factores de riesgo psicosocial?',
  'Características físicas del lugar de trabajo',
  'Características de las condiciones laborales y su organización que impactan la salud de las personas',
  'Equipos de protección personal',
  'Beneficios sociales del trabajador',
  'b'),
(ex2_id, 3,
  '¿Cuál de estos es un factor de riesgo psicosocial?',
  'Buena iluminación en el puesto',
  'Equipos ergonómicos',
  'Síndrome de Burnout, acoso laboral y estrés laboral',
  'Capacitaciones frecuentes',
  'c'),
(ex2_id, 4,
  '¿Cómo se define el estrés laboral?',
  'Sensación de alegría y motivación en el trabajo',
  'Conjunto de reacciones emocionales, cognitivas, fisiológicas y conductuales ante aspectos adversos del entorno laboral',
  'Estado de relajación total en el trabajo',
  'Motivación para trabajar más horas',
  'b'),
(ex2_id, 5,
  '¿Cuáles son enfermedades que puede causar el estrés laboral crónico?',
  'Mayor rendimiento deportivo y energía',
  'Hipertensión arterial, úlcera péptica y asma bronquial',
  'Mejor digestión y sueño reparador',
  'Aumento de energía y concentración',
  'b'),
(ex2_id, 6,
  'No cuidar la salud mental a nivel cognitivo afecta principalmente:',
  'El color de piel del trabajador',
  'La capacidad para concentrarse, recordar, tomar decisiones y resolver problemas',
  'La velocidad al caminar',
  'El apetito únicamente',
  'b'),
(ex2_id, 7,
  '¿Cuál es una ventaja del bienestar personal en el trabajo?',
  'Aumenta el ausentismo laboral',
  'Reduce las quejas, mejora el clima laboral y eleva la moral de los trabajadores',
  'Incrementa los conflictos entre compañeros',
  'Disminuye la productividad del equipo',
  'b'),
(ex2_id, 8,
  '¿Qué técnica práctica ayuda a calmar el sistema nervioso de forma inmediata?',
  'Tomar café en exceso',
  'Respirar profundo, ya que envía señales al cerebro para calmarse y reduce el ritmo cardíaco',
  'Trabajar más horas seguidas sin parar',
  'Ver noticias antes de dormir',
  'b'),
(ex2_id, 9,
  '¿Qué principio es clave en la relación entre compañeros de trabajo?',
  'Competir constantemente para destacar',
  'Escuchar y respetar las ideas y opiniones de los demás para una interacción equitativa y justa',
  'Ignorar los problemas del equipo',
  'Trabajar siempre de forma individual',
  'b'),
(ex2_id, 10,
  '¿Qué incluye el estilo de vida como herramienta para la salud mental?',
  'Solo tomar medicamentos recetados',
  'Moverse, nutrirse, descansar y buscar apoyo social',
  'Trabajar sin pausas para ser más productivo',
  'Aislarse de los compañeros para concentrarse',
  'b');

RAISE NOTICE 'Exámenes creados: % y %', ex1_id, ex2_id;
END $$;
